---
title: "Topic 1: Getting Started with GitHub"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Creating an Account

If you don't already have a GitHub account, go to [GitHub](https://github.com/join) and create one. Here are helpful considerations for choosing a username: [happygitwithr.com/github-acct.html](https://happygitwithr.com/github-acct.html)

## Connecting GitHub to RStudio

You should already have git on your device, but let's check for it anyway.

-   Open RStudio

-   In the Terminal, run the following command:

```         
where git
```

-   If after running that you get something that looks like a file path to git on your computer, then you have git installed. For example, that might return something like this (or it could differ a bit): `/usr/local/bin/git`. If you instead get no response at all, you should download & install git from here: [**git-scm.com/downloads**](https://git-scm.com/downloads)

<!-- -->

-   In RStudio, open the Terminal. Run the following commands (by pressing Enter after each line), replacing the username (keep the quotation marks!) and email with your username and email used for your GitHub account.

```         
git config --global user.name "Jane Doe" git config --global user.email janedoe@example.com
```

-   Then, in the Terminal run the following, carefully checking that the name and email returned match your GitHub information:

```         
git config --list --global
```
